baseURL: "https://sheetal-jadhav.github.io/"
title: Sheetal Jadhav
theme: PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20
taxonomies:
  tag: tags
menu:
  main:
    - name: CV
      url: cv/
      weight: 1
    - name: Projects
      url: papers/
      weight: 2
    - name: Study Notes
      url: notes/
      weight: 3
    - name: Personal Essays
      url: books/
      weight: 4
    - name: Sci Comm.
      url: https://www.instagram.com/onlybrainytales/
      weight: 5
params:
  description: "This website hosts Sheetal Jadhav's research papers, course materials, projects, curriculum vitae, and contact information."
  author: Sheetal Jadhav
  DateFormat: "January 2006"
  defaultTheme: light
  hideFooter: false
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: false
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true
  profileMode:
    enabled: true
    title: Sheetal Jadhav
    subtitle: "Hi there! Welcome to my website. My name is Sheetal Jadhav. I am an electronics engineer pursuing research in computational neuroscience. I am currently transitioning into a PhD in Tristan Stöber's lab at the University of Göttingen, where I will work on building brain-inspired AGI models. My research lies at the intersection of neural dynamics, sequence learning, and biophysical modeling, with a focus on spiking neural networks, STDP-based learning rules, and hippocampal cognitive maps. Previously, I worked in a songbird lab, where I conducted neuroelectrophysiological studies on the songbird brain to understand language syntax. My research so far has been highly interdisciplinary, spanning theoretical, neurobiological, and electrical labs. Outside of research, I love science communication and writing. I run Brainy Tales, an educational platform on neuroscience, and write on Substack about the intersections of science and politics."
    imageUrl: "picture.jpeg"
    imageWidth: 160
    imageHeight: 160
    buttons:
      - name: CV
        url: cv/
      - name: Projects
        url: papers/
      - name: Study Notes
        url: notes/
      - name: Personal Essays
        url: books/
      - name: Sci Comm.
        url: https://www.instagram.com/onlybrainytales/
  socialIcons:
    - name: Substack
      url: https://substack.com/@yourthoughtfully
    - name: GoogleScholar
      url: https://scholar.google.com/citations?user=cL23W-4AAAAJ
    - name: GitHub
      url: https://github.com/sheetal-jadhav
    - name: Twitter
      url: https://x.com/_curiousneuron
    - name: Bluesky
      url: https://bsky.app/profile/thecuriousneuron.bsky.social
    - name: Location
      url: location/
  assets:
    disableScrollBarStyle: true
  cover:
    hiddenInList: false
    hiddenInSingle: true
  label:
    text: "Sheetal Jadhav"
    icon: favicon.ico
    iconHeight: 18
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: autumn
  tableOfContents:
    endLevel: 2
